import React, { useEffect, useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import AdminLayout from "../layout/AdminLayout";
import { Document, Page, Text, View, StyleSheet, PDFDownloadLink, Font } from "@react-pdf/renderer";

// Register fonts if needed, simple standard fonts work out of box
Font.register({
    family: 'Oswald',
    src: 'https://fonts.gstatic.com/s/oswald/v13/Y_TKV6o8WovbUd3m_X9aAA.ttf'
});

const styles = StyleSheet.create({
    page: { flexDirection: 'column', padding: 30, backgroundColor: '#FFFFFF' },
    section: { margin: 10, padding: 10, flexGrow: 1 },
    header: { fontSize: 24, marginBottom: 20, textAlign: 'center', fontFamily: 'Oswald' },
    subHeader: { fontSize: 18, borderBottom: '1px solid #000', marginBottom: 10, marginTop: 15 },
    row: { flexDirection: 'row', marginBottom: 5 },
    label: { fontSize: 12, fontWeight: 'bold', width: 120 },
    value: { fontSize: 12, flex: 1 },
    text: { fontSize: 11, lineHeight: 1.5, textAlign: 'justify' },
    disclaimer: { fontSize: 10, marginTop: 30, color: 'grey', textAlign: 'center' }
});

// PDF Document Component
const PatentPDFDocument = ({ filing }) => (
    <Document>
        <Page size="A4" style={styles.page}>
            <View style={styles.section}>
                <Text style={styles.header}>Patent Application Dossier</Text>
                <Text style={{ textAlign: 'center', fontSize: 12, marginBottom: 20 }}>Ref: {filing.applicationNumber || "PENDING"}</Text>

                <Text style={styles.subHeader}>Bibliographic Data</Text>
                <View style={styles.row}><Text style={styles.label}>Title:</Text><Text style={styles.value}>{filing.title}</Text></View>
                <View style={styles.row}><Text style={styles.label}>Technical Field:</Text><Text style={styles.value}>{filing.technicalField}</Text></View>
                <View style={styles.row}><Text style={styles.label}>Filing Date:</Text><Text style={styles.value}>{filing.filingDate || "N/A"}</Text></View>
                <View style={styles.row}><Text style={styles.label}>Status:</Text><Text style={styles.value}>{filing.status}</Text></View>
                <View style={styles.row}><Text style={styles.label}>Applicant Type:</Text><Text style={styles.value}>{filing.applicantType}</Text></View>
                <View style={styles.row}><Text style={styles.label}>Jurisdiction:</Text><Text style={styles.value}>{filing.jurisdiction}</Text></View>

                <Text style={styles.subHeader}>Abstract</Text>
                <Text style={styles.text}>{filing.abstractText}</Text>

                <Text style={styles.subHeader}>Problem Statement</Text>
                <Text style={styles.text}>{filing.problemStatement}</Text>

                <Text style={styles.subHeader}>Novelty Claims</Text>
                <Text style={styles.text}>{filing.novelty}</Text>

                <Text style={styles.disclaimer}>Generated by Global IPI Platform Admin Portal</Text>
            </View>
        </Page>
    </Document>
);

const AdminFilingDetail = () => {
    const { id } = useParams();
    const navigate = useNavigate();
    const [filing, setFiling] = useState(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        fetchFilingDetails();
    }, [id]);

    const fetchFilingDetails = async () => {
        try {
            const token = localStorage.getItem("adminToken");
            const res = await fetch(`http://localhost:8081/api/admin/patent-filings/${id}`, {
                headers: { Authorization: `Bearer ${token}` }
            });
            if (res.ok) {
                const data = await res.json();
                setFiling(data);
            } else {
                console.error("Failed to fetch filing");
            }
        } catch (err) {
            console.error(err);
        } finally {
            setLoading(false);
        }
    };

    if (loading) return (
        <AdminLayout>
            <div className="flex justify-center items-center h-full text-white">Loading...</div>
        </AdminLayout>
    );

    if (!filing) return (
        <AdminLayout>
            <div className="text-white text-center mt-10">Filing not found</div>
        </AdminLayout>
    );

    return (
        <AdminLayout>
            <div className="max-w-5xl mx-auto space-y-6">
                {/* Header with Actions */}
                <div className="flex items-center justify-between bg-[#161b22] border border-[#30363d] p-6 rounded-xl shadow-lg">
                    <div>
                        <div className="flex items-center gap-3">
                            <button onClick={() => navigate(-1)} className="text-gray-400 hover:text-white">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M19 12H5M12 19l-7-7 7-7" /></svg>
                            </button>
                            <h1 className="text-2xl font-bold text-white">{filing.title}</h1>
                        </div>
                        <p className="text-gray-400 mt-1 ml-9">App #: <span className="font-mono text-purple-400">{filing.applicationNumber || "PENDING"}</span> • Filed: {filing.filingDate}</p>
                    </div>
                    <div className="flex gap-3">
                        <PDFDownloadLink document={<PatentPDFDocument filing={filing} />} fileName={`Patent_${filing.applicationNumber || 'Draft'}.pdf`}>
                            {({ loading }) => (
                                <button className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg transition-colors font-medium">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" /><polyline points="7 10 12 15 17 10" /><line x1="12" y1="15" x2="12" y2="3" /></svg>
                                    {loading ? 'Generating PDF...' : 'Download Dossier'}
                                </button>
                            )}
                        </PDFDownloadLink>
                    </div>
                </div>

                {/* Content Grid */}
                <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                    {/* Main Info */}
                    <div className="lg:col-span-2 space-y-6">
                        <div className="bg-[#161b22] border border-[#30363d] rounded-xl p-6 shadow-lg">
                            <h3 className="text-lg font-semibold text-white mb-4 border-b border-[#30363d] pb-2">Technical Details</h3>
                            <div className="space-y-4">
                                <div>
                                    <label className="text-xs text-gray-500 uppercase font-semibold tracking-wider">Abstract</label>
                                    <p className="text-gray-300 leading-relaxed mt-1 text-sm bg-[#0d1117] p-3 rounded-lg border border-[#30363d]">{filing.abstractText}</p>
                                </div>
                                <div className="grid grid-cols-2 gap-4">
                                    <div>
                                        <label className="text-xs text-gray-500 uppercase font-semibold tracking-wider">Technical Field</label>
                                        <p className="text-white mt-1">{filing.technicalField}</p>
                                    </div>
                                    <div>
                                        <label className="text-xs text-gray-500 uppercase font-semibold tracking-wider">Jurisdiction</label>
                                        <p className="text-white mt-1">{filing.jurisdiction}</p>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div className="bg-[#161b22] border border-[#30363d] rounded-xl p-6 shadow-lg">
                            <h3 className="text-lg font-semibold text-white mb-4 border-b border-[#30363d] pb-2">Full Description</h3>
                            <div className="space-y-4">
                                <div>
                                    <label className="text-xs text-gray-500 uppercase font-semibold tracking-wider">Problem Statement</label>
                                    <p className="text-gray-300 leading-relaxed mt-1 text-sm">{filing.problemStatement || "Not provided"}</p>
                                </div>
                                <div>
                                    <label className="text-xs text-gray-500 uppercase font-semibold tracking-wider">Novelty Claims</label>
                                    <p className="text-gray-300 leading-relaxed mt-1 text-sm">{filing.novelty || "Not provided"}</p>
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* Sidebar Info - Documents & Status */}
                    <div className="space-y-6">
                        <div className="bg-[#161b22] border border-[#30363d] rounded-xl p-6 shadow-lg">
                            <h3 className="text-lg font-semibold text-white mb-4 border-b border-[#30363d] pb-2">Documents</h3>
                            <ul className="space-y-3">
                                <DocumentItem label="Specification" status="Available" />
                                <DocumentItem label="Claims" status="Available" />
                                <DocumentItem label="Drawings" status={filing.drawingsFilePaths && filing.drawingsFilePaths.length > 0 ? `${filing.drawingsFilePaths.length} Files` : "None"} />
                            </ul>
                        </div>

                        <div className="bg-[#161b22] border border-[#30363d] rounded-xl p-6 shadow-lg">
                            <h3 className="text-lg font-semibold text-white mb-4 border-b border-[#30363d] pb-2">Filing Metadata</h3>
                            <div className="space-y-3 text-sm">
                                <div className="flex justify-between">
                                    <span className="text-gray-500">Status</span>
                                    <span className={`px-2 py-0.5 rounded text-xs font-semibold ${getStatusColor(filing.status)}`}>{filing.status}</span>
                                </div>
                                <div className="flex justify-between">
                                    <span className="text-gray-500">Applicant Type</span>
                                    <span className="text-white">{filing.applicantType}</span>
                                </div>
                                <div className="flex justify-between">
                                    <span className="text-gray-500">Payment</span>
                                    <span className="text-green-400 capitalize">{filing.paymentStatus}</span>
                                </div>
                                <div className="flex justify-between">
                                    <span className="text-gray-500">Last Updated</span>
                                    <span className="text-white">{new Date(filing.updatedAt).toLocaleDateString()}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </AdminLayout>
    );
};

const DocumentItem = ({ label, status }) => (
    <li className="flex items-center justify-between p-3 bg-[#0d1117] border border-[#30363d] rounded-lg group hover:border-blue-500/50 transition-colors">
        <div className="flex items-center gap-3">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-blue-400"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" /><polyline points="14 2 14 8 20 8" /><line x1="16" y1="13" x2="8" y2="13" /><line x1="16" y1="17" x2="8" y2="17" /><polyline points="10 9 9 9 8 9" /></svg>
            <span className="text-gray-300 font-medium text-sm">{label}</span>
        </div>
        <span className="text-xs text-gray-500">{status}</span>
    </li>
);

const getStatusColor = (status) => {
    switch (status?.toUpperCase()) {
        case 'GRANTED': return 'bg-emerald-500/20 text-emerald-400';
        case 'FILED': return 'bg-blue-500/20 text-blue-400';
        case 'PENDING': return 'bg-yellow-500/20 text-yellow-400';
        default: return 'bg-gray-500/20 text-gray-400';
    }
};

export default AdminFilingDetail;
